### ISSUE TITLE
battle3 en battle4?

### ISSUE THREAD

**Issue by henkburgstra** [thomas64/pyRPG#2]
Ik ken de achtergrond van battle1 en battle2 en ik weet dat je battle3 zou aanmaken, maar wat is de bedoeling van battle4? Zal ik daar mijn opzet in zetten?

**Comment by thomas64** [comment]
Battle 3 en 4 zijn op dit moment nog een exacte kopie van elkaar. Maar ik had battle 3 voor jou bedacht, en voor mezelf battle 4, ook om te proberen ed.

**Comment by henkburgstra** [comment]
OK, duidelijk
